# Generated by Django 5.2.3 on 2025-07-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_post_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleuserlikes',
            old_name='post',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
        migrations.AlterUniqueTogether(
            name='articleuserlikes',
            unique_together={('user', 'article')},
        ),
    ]
